ACTION_INCORRECT = 20001
ROLE_ALREADY_EXISTS = 20002
ROLE_ALREADY_DELETE = 20003
ROLE_ALREADY_NOT_EXISTS = 20004
COURSE_ALREADY_EXISTS = 20005
ORGANIZATION_TYPE_NOT_EXISTS = 20006
PARENT_ORGANIZATION_NAME_NOT_EXITS = 20007
ORGANIZATION_NAME_EXITS = 20008

J_MSG = {ROLE_ALREADY_EXISTS: '角色已存在', ACTION_INCORRECT: '参数action不正确', ROLE_ALREADY_DELETE: '角色已删除',
         ROLE_ALREADY_NOT_EXISTS: '角色不存在', COURSE_ALREADY_EXISTS: '课程不存在', ORGANIZATION_TYPE_NOT_EXISTS: '组织类型不存在',
         PARENT_ORGANIZATION_NAME_NOT_EXITS: '父级组织名称不存在',ORGANIZATION_NAME_EXITS:'组织名称已存在', }
